# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AuthServ.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x41uthServ.proto\x12\x03\x43\x41S\"&\n\x15GetIdFromEmailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"$\n\x16GetIdFromEmailResponse\x12\n\n\x02id\x18\x01 \x01(\x03\"4\n\x11RegistrationInput\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"8\n\x1dRegistrationVerificationInput\x12\x17\n\x0frandomDataToken\x18\x01 \x01(\t\"\x1d\n\tAuthInput\x12\x10\n\x08jwtToken\x18\x01 \x01(\t\"4\n\x11PasswordAuthInput\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"2\n\x12RegistrationResult\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x0c\n\x04isOk\x18\x02 \x01(\x08\":\n\x1eRegistrationVerificationResult\x12\x18\n\x10response_message\x18\x01 \x01(\t\"/\n\nAuthResult\x12\x0e\n\x06userId\x18\x01 \x01(\x03\x12\x11\n\tnextToken\x18\x02 \x01(\t\"7\n\x12PasswordAuthResult\x12\x10\n\x08jwtToken\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\x32\xf2\x02\n\x14\x41uthAndRegistService\x12=\n\nTryRegistr\x12\x16.CAS.RegistrationInput\x1a\x17.CAS.RegistrationResult\x12Z\n\x0fTryVerifRegistr\x12\".CAS.RegistrationVerificationInput\x1a#.CAS.RegistrationVerificationResult\x12/\n\x0c\x41uthenticate\x12\x0e.CAS.AuthInput\x1a\x0f.CAS.AuthResult\x12\x43\n\x10\x41uthFromPassword\x12\x16.CAS.PasswordAuthInput\x1a\x17.CAS.PasswordAuthResult\x12I\n\x0eGetIdFromEmail\x12\x1a.CAS.GetIdFromEmailRequest\x1a\x1b.CAS.GetIdFromEmailResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AuthServ_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETIDFROMEMAILREQUEST._serialized_start=23
  _GETIDFROMEMAILREQUEST._serialized_end=61
  _GETIDFROMEMAILRESPONSE._serialized_start=63
  _GETIDFROMEMAILRESPONSE._serialized_end=99
  _REGISTRATIONINPUT._serialized_start=101
  _REGISTRATIONINPUT._serialized_end=153
  _REGISTRATIONVERIFICATIONINPUT._serialized_start=155
  _REGISTRATIONVERIFICATIONINPUT._serialized_end=211
  _AUTHINPUT._serialized_start=213
  _AUTHINPUT._serialized_end=242
  _PASSWORDAUTHINPUT._serialized_start=244
  _PASSWORDAUTHINPUT._serialized_end=296
  _REGISTRATIONRESULT._serialized_start=298
  _REGISTRATIONRESULT._serialized_end=348
  _REGISTRATIONVERIFICATIONRESULT._serialized_start=350
  _REGISTRATIONVERIFICATIONRESULT._serialized_end=408
  _AUTHRESULT._serialized_start=410
  _AUTHRESULT._serialized_end=457
  _PASSWORDAUTHRESULT._serialized_start=459
  _PASSWORDAUTHRESULT._serialized_end=514
  _AUTHANDREGISTSERVICE._serialized_start=517
  _AUTHANDREGISTSERVICE._serialized_end=887
# @@protoc_insertion_point(module_scope)
